version: "3.9"
services:
  web:
    build: 
      context: src
      args:
        DISABLE_OPCACHE_PRE_COMPILATION: false
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/efs:/mnt/share
      - ./tmp/tmp:/tmp
      - ./tmp/log:/var/log
      - ./src/:/src
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
      - s3mock
    environment:
      REDIS_CFG_ENDPOINT: 'redis'
      REDIS_PORT: 6379
      DB_HOST: 'mysql'
      DB_NAME: 'mysql'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      EFS_PATH: '/mnt/share'
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
      WP_ENV: development
      WP_DEFAULT_THEME: blocksy
      S3_ENDPOINT: 'http://s3mock:9090'
      DISABLE_OPCACHE_PRE_COMPILATION: false
    # Just use root on Mac
    # Actually, use a random id - closer to lambda
    user: 9999:9999
    read_only: true
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
    command: redis-server --appendonly yes
  s3mock:
    image: adobe/s3mock
    ports:
      - "9090:9090"
    volumes:
      - ./tmp/s3mock:/var/lib/s3mock
    environment:
      initialBuckets: test-bucket

